[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3.2"
regex = "1"
base64 = "0.22.1"
zip = "2.1.3"
dotenv = "0.15.0"
reqwest = { version = "0.12.4", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }